// src/data/cityData.ts
export const cityDetails = [
    {
      name: "Shimla",
      description: "Shimla, the Queen of Hills, is a beautiful hill station in Himachal Pradesh. Known for its colonial architecture and lush green landscapes, Shimla offers visitors a perfect mix of adventure, history, and tranquility.",
      attractions: [
        "Mall Road - The heart of Shimla, perfect for shopping, dining, and enjoying the lively atmosphere.",
        "Jakhu Temple - A historic temple dedicated to Lord Hanuman, offering panoramic views of the surrounding mountains.",
        "Kufri - A popular spot for adventure sports, including skiing in winter and horse riding in summer.",
        "Christ Church - The second oldest church in North India, renowned for its Neo-Gothic architecture.",
        "Summer Hill - A picturesque spot known for its natural beauty and peaceful vibe.",
        "The Ridge - A bustling promenade that provides stunning views of the surrounding mountains.",
        "Viceregal Lodge - The former summer residence of the British Viceroy, now a heritage museum.",
      ],
      hiddenGems: [
        "Explore the quiet beauty of the Glen for peaceful hikes and serene nature trails.",
        "Visit Tara Devi Temple for panoramic views away from the crowds and a spiritual atmosphere.",
        "The Annandale – An old colonial playground with scenic views and a historic air.",
        "The Lakkar Bazaar – A charming market with wooden handicrafts and souvenirs.",
      ],
      history: "Shimla became the summer capital of British India in 1864, established as a hill station to escape the summer heat. The town has a rich colonial legacy, evident in its Victorian-era buildings and charming streets. The town’s development was influenced by its strategic location and was a prominent center for British politics and leisure. The town hosted the Simla Conference in 1945, which was significant for India's post-independence discussions.",
      bestTimeToVisit: "March to June offers pleasant weather with blooming flowers and lush landscapes, while December to February is perfect for snow and winter sports.",
      localCuisine: [
        "Sidu - Steamed wheat bread served with a variety of chutneys and curries.",
        "Chana Madra - A traditional Himachali dish made of chickpeas cooked in yogurt and a variety of spices.",
        "Tibetan momos - Dumplings filled with meat or vegetables, a popular snack in the area.",
        "Himachali Thali - A platter featuring various regional dishes like Rajma, Dal, and seasonal vegetables.",
        "Chana Dal Curry - A flavorful curry made with chickpeas and aromatic spices.",
      ],
      festivals: [
        "Summer Festival - A week-long celebration featuring music, dance, and local arts.",
        "Diwali - The festival of lights, celebrated with great enthusiasm across the town.",
        "Lohri - A traditional Punjabi festival marking the harvest season, celebrated with bonfires and dance.",
        "Baisakhi - A harvest festival celebrated with music, dance, and food.",
        "Shimla Winter Carnival - A winter event that features traditional music, local dance performances, and local cuisine.",
      ],
      image: "https://plus.unsplash.com/premium_photo-1697729690458-2d64ca777c04?w=500",
    },
    {
      name: "Manali",
      description: "Manali, a high-altitude Himalayan resort town in Himachal Pradesh, is famous for its breathtaking landscapes, vibrant Tibetan culture, and outdoor adventure activities.",
      attractions: [
        "Rohtang Pass - A high mountain pass offering sweeping views of the surrounding valleys and a range of snow activities.",
        "Solang Valley - Known for paragliding, zorbing, and skiing.",
        "Hadimba Temple - A unique wooden temple dedicated to Hadimba, located amidst the beautiful forest of Manali.",
        "Old Manali - A charming area known for its laid-back vibe, cafes, and traditional wooden houses.",
        "Vashisht Hot Springs - Natural hot springs that are believed to have healing properties.",
        "Manu Temple - A sacred temple dedicated to Sage Manu, offering spiritual solace and panoramic views.",
      ],
      hiddenGems: [
        "The serene village of Naggar, known for its art galleries, historical castle, and beautiful views of the Kullu Valley.",
        "Jana Waterfall, perfect for a refreshing dip in solitude and surrounded by lush greenery.",
        "The Old Manali Cafes – A hub for backpackers offering local and international cuisine with stunning views.",
        "The Raison village, known for its apple orchards and picturesque landscapes.",
      ],
      history: "Manali has been a spiritual and cultural center for centuries and was historically part of the Kullu Valley Kingdom. Its status as a tourist destination grew significantly after the 1950s when it became accessible via roads and attracted both domestic and international travelers. The town is named after the Hindu sage Manu, believed to be the creator of human civilization according to Hindu mythology.",
      bestTimeToVisit: "May to October for adventure sports and pleasant weather; December to February for snowfall and winter sports.",
      localCuisine: [
        "Sidu - A traditional Himachali bread, usually served with chutney or curry.",
        "Tibetan Thukpa - A noodle soup popular in the region with rich, spicy flavors.",
        "Chana Madra - A dish made from chickpeas, yogurt, and a mixture of aromatic spices.",
        "Kullu Trout - A specialty fish dish found in the Kullu Valley.",
        "Dham - A traditional festive dish usually served during weddings or religious occasions.",
      ],
      festivals: [
        "Dussehra - Celebrated in the Kullu Valley with grand processions, traditional dances, and rituals.",
        "Manali Winter Carnival - A celebration of the winter season with performances, local food, and crafts.",
        "Tibetan New Year - Also known as Losar, a significant event for the Tibetan community, marked by prayer rituals and cultural activities.",
        "Baisakhi - Celebrated by the local community with traditional dances, music, and festive foods.",
        "Rath Yatra - A local festival that involves a procession of chariots and is accompanied by music and prayers.",
      ],
      image: "https://cdn.pixabay.com/photo/2024/07/20/15/52/mountains-8908538_640.jpg",
    },
    {
      name: "Goa",
      description: "Goa, India's smallest state, is celebrated for its stunning coastline, golden beaches, and lively nightlife. It is a perfect blend of Portuguese heritage and Indian culture.",
      attractions: [
        "Baga Beach - A popular beach known for its nightlife, water sports, and beach shacks.",
        "Dudhsagar Falls - A majestic four-tiered waterfall located in the Bhagwan Mahaveer Wildlife Sanctuary.",
        "Fort Aguada - A historic fort built by the Portuguese to defend against the Marathas and Dutch.",
        "Calangute Beach - Known as the 'Queen of Beaches,' ideal for sunbathing and beach sports.",
        "Anjuna Flea Market - A vibrant market where you can buy everything from clothes to jewelry and souvenirs.",
        "Chapora Fort - A fort offering panoramic views of the Arabian Sea and a famous location for photography.",
      ],
      hiddenGems: [
        "Palolem Beach for a sunrise view, often less crowded and perfect for morning yoga.",
        "The spice plantations in the hinterlands for a unique local experience and guided tours.",
        "The quiet village of Saligao, known for its Portuguese-style architecture and tranquil vibe.",
        "Divar Island – A lesser-known island offering peaceful nature walks and historical sites.",
      ],
      history: "Goa was ruled by the Portuguese for over 450 years, which has left a significant mark on its culture, cuisine, and architecture. It became a part of India in 1961 after a liberation movement. The colonial period saw Goa develop a unique blend of European and Indian culture, seen in its churches, forts, and traditions.",
      bestTimeToVisit: "November to February for the most pleasant weather; June to September for monsoon lovers and fewer crowds. December is also notable for the Goa Carnival and Christmas celebrations.",
      localCuisine: [
        "Goan Prawn Curry - A rich and spicy curry made with coconut milk and Goan spices.",
        "Bebinca - A traditional Goan dessert made with coconut milk, sugar, and egg yolks.",
        "Prawn Balchão - A tangy and spicy prawn dish with a rich blend of Goan spices.",
        "Fish Recheado - A spicy and flavorful dish made with marinated fish stuffed with a masala filling.",
        "Kaju Curry - A unique Goan curry made with cashews and traditional spices.",
      ],
      festivals: [
        "Goa Carnival - The most vibrant and colorful festival, celebrated with parades, dances, and music.",
        "Christmas - Celebrated with fervor, including midnight mass, traditional food, and music.",
        "Ganesh Chaturthi - A major festival where large idols of Lord Ganesha are paraded through the streets and immersed in water.",
        "Shigmo Festival - The Goan version of Holi, with traditional dance and music performances.",
        "Diwali - Celebrated with lighting oil lamps, bursting fireworks, and traditional sweets.",
      ],
      image: "https://cdn.pixabay.com/photo/2016/02/19/10/00/beach-1209062_640.jpg",
    },
    {
      name: "Jaipur",
      description: "Jaipur, the Pink City, is known for its royal palaces, grand forts, and bustling bazaars. It epitomizes the grandeur and history of Rajasthan.",
      attractions: [
        "Hawa Mahal - The iconic 'Palace of Winds,' known for its unique five-story facade with hundreds of small windows.",
        "Amber Fort - A majestic fort showcasing a blend of Hindu and Mughal architecture, located on a hilltop overlooking Maota Lake.",
        "City Palace - A grand complex of palaces, courtyards, and museums showcasing Rajasthani royal heritage.",
        "Jantar Mantar - An ancient observatory with large instruments for astronomical observations, recognized as a UNESCO World Heritage Site.",
        "Nahargarh Fort - Located on the Aravalli hills, this fort provides panoramic views of the city.",
        "Jal Mahal - A beautiful palace located in the middle of Man Sagar Lake, offering breathtaking views at sunset.",
      ],
      hiddenGems: [
        "Panna Meena ka Kund - An ancient stepwell known for its architectural beauty and historical significance.",
        "The artisan workshops in Johari Bazaar – A vibrant place for traditional jewelry and crafts.",
        "The Albert Hall Museum – A museum that showcases Rajasthan’s rich culture and art.",
        "Gaitore Ki Chhatriyan – A royal cenotaph that provides insight into the history of Jaipur’s rulers.",
      ],
      history: "Founded in 1727 by Maharaja Jai Singh II, Jaipur was planned according to Vastu Shastra, a traditional Hindu system of architecture. The city became the first planned city of India and served as the capital of the princely state of Jaipur. Its pink hue comes from a tradition that started in 1876 when the city was painted pink to welcome the Prince of Wales, which later became a symbol of hospitality.",
      bestTimeToVisit: "October to March for the most pleasant sightseeing weather. The weather is cooler and perfect for outdoor activities.",
      localCuisine: [
        "Dal Baati Churma - A classic Rajasthani dish of lentils, baked wheat balls, and sweet crumbled bread.",
        "Laal Maas - A spicy meat curry made with red chilies and rich spices.",
        "Pyaaz Kachori - A famous snack made of deep-fried pastry stuffed with spicy onion filling.",
        "Ghevar - A traditional Rajasthani sweet made with flour, sugar, and ghee, often served during festivals.",
        "Ker Sangri - A dish made with wild beans and desert berries, unique to the region.",
      ],
      festivals: [
        "Jaipur Literature Festival - One of the largest literary festivals in Asia, attracting authors, poets, and intellectuals from around the world.",
        "Teej Festival - A vibrant festival celebrating the arrival of monsoon, with traditional dance, music, and rituals.",
        "Diwali - Celebrated with grandeur, the city comes alive with lights, fireworks, and festivities.",
        "Makar Sankranti - A festival that marks the end of winter and the beginning of the harvest season, celebrated with kite flying.",
        "Elephant Festival - A special event that showcases decorated elephants, cultural performances, and traditional games.",
      ],
      image: "https://cdn.pixabay.com/photo/2021/04/06/11/22/hawa-mahal-6156123_1280.jpg",
    },
    {
      name: "Varanasi",
      description: "Varanasi, the spiritual capital of India, is believed to be one of the oldest cities in the world. Known for its spiritual significance and the majestic River Ganges.",
      attractions: [
        "Dashashwamedh Ghat - One of the most famous ghats along the Ganges, known for its evening Aarti ceremony.",
        "Kashi Vishwanath Temple - A highly revered Hindu temple dedicated to Lord Shiva.",
        "Sarnath - A place of great historical and religious significance, where Lord Buddha gave his first sermon.",
        "Manikarnika Ghat - A ghat with deep religious significance, known for its rituals related to death.",
        "Ramnagar Fort - A historical fort located on the banks of the Ganges, known for its museum and unique architecture.",
        "Tulsi Manas Temple - A modern temple dedicated to Lord Rama, built at the site where the epic Ramcharitmanas was composed.",
      ],
      hiddenGems: [
        "Alamnagar Palace, less-visited and full of history, with intricate architecture and stunning views of the Ganges.",
        "Gyanvapi Mosque – A historic mosque with a rich history that dates back to the Mughal period.",
        "The narrow lanes of Varanasi – Perfect for discovering local crafts and engaging with artisans.",
        "The Banaras Hindu University campus – One of India's oldest and most prestigious educational institutions.",
      ],
      history: "Varanasi has been a center of learning, religion, and trade for thousands of years. It is considered a holy city in Hinduism and has influenced cultural practices for generations. Varanasi is believed to have been founded by Lord Shiva and has been an essential part of Hindu mythology and the history of India. It has been visited by numerous spiritual leaders and scholars over the centuries.",
      bestTimeToVisit: "October to March for comfortable weather and cultural festivities. The weather is cool and pleasant during these months.",
      localCuisine: [
        "Kachori Sabzi - A popular breakfast dish of deep-fried kachori served with spicy potato curry.",
        "Banarasi Paan - A unique betel leaf preparation known for its refreshing taste.",
        "Lassi - A sweet, chilled yogurt drink, famous for its rich and creamy texture.",
        "Chaat - A spicy and tangy snack made with a mix of potatoes, chickpeas, chutney, and spices.",
        "Malaiyo - A special dish served during winters, made with milk and saffron.",
      ],
      festivals: [
        "Kumbh Mela - One of the largest religious gatherings in the world, held every 12 years in Varanasi.",
        "Diwali - Celebrated with grandeur, the city is illuminated with thousands of diyas and lights.",
        "Holi - The festival of colors, celebrated with dance, music, and traditional sweets.",
        "Ganga Dussehra - A festival celebrating the descent of the Ganges river, with rituals and prayers performed at various ghats.",
        "Makar Sankranti - Marked by the floating of kites and visits to the Ganges for purification.",
      ],
      image: "https://cdn.pixabay.com/photo/2017/06/04/18/00/varanasi-2371751_640.jpg",
    },
    {
      name: "Munnar",
      description: "Munnar, located in Kerala, is famed for its tea plantations, mist-covered hills, and serene atmosphere. It’s a perfect escape for nature lovers.",
      attractions: [
        "Tea Museum - A museum dedicated to the history of tea cultivation and its significance in the region.",
        "Mattupetty Dam - A reservoir surrounded by lush greenery, offering boating and wildlife sightings.",
        "Eravikulam National Park - A sanctuary known for its habitat of the endangered Nilgiri Tahr and stunning views.",
        "Attukad Waterfalls - A beautiful and serene waterfall, perfect for trekking and nature walks.",
        "Kundala Lake - A picturesque lake known for pedal boating and breathtaking views.",
        "Echo Point – A scenic spot known for its echo phenomenon and panoramic views.",
      ],
      hiddenGems: [
        "Marayoor for its sandalwood forests and historical caves with ancient rock paintings.",
        "The hills of Anamudi Peak, the highest in South India, ideal for trekking and nature exploration.",
        "Chinnakanal Waterfalls – Less-crowded and perfect for a peaceful day amidst nature.",
        "The spice plantations of Munnar, where you can learn about and sample local spices.",
      ],
      history: "Munnar’s development as a major tea-growing region began in the 19th century when the British established large plantations. The region’s name, derived from 'Munnu' (three) and 'Aaru' (river), refers to the meeting point of three rivers. The British used Munnar as a summer retreat, establishing its legacy of plantations and tea culture. It has since become a significant center for eco-tourism.",
      bestTimeToVisit: "September to March for cooler temperatures and clear views of the hills and plantations.",
      localCuisine: [
        "Kerala Sadya - A traditional vegetarian feast served on a banana leaf with various dishes.",
        "Appam and Stew - A dish consisting of rice pancakes served with a coconut milk-based vegetable or meat stew.",
        "Karimeen Pollichathu - A fish dish with pearl spot fish cooked in banana leaves with spices.",
        "Tea with Local Snacks – Munnar’s tea and traditional snacks like banana chips and pazhampori.",
        "Puttu and Kadala Curry – A breakfast staple made of steamed rice flour and coconut served with spicy chickpeas.",
      ],
      festivals: [
        "Onam - The harvest festival celebrated with grand feasts and cultural performances.",
        "Makar Sankranti - Celebrated with kite flying and traditional sweets.",
        "Thekkady Wildlife Festival – A celebration showcasing the region's natural wildlife and eco-tourism.",
        "Vishu - The Kerala New Year marked by fireworks, feasting, and traditional rituals.",
        "Chutney Festival – A unique event celebrating local food and dishes, often paired with live music and dances.",
      ],
      image: "https://cdn.pixabay.com/photo/2020/01/16/04/52/munnar-4769654_1280.jpg",
    },
  ];
